name: keno_plus
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  crypto: ^3.0.6
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  go_router: ^15.1.1
  intl: ^0.20.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/kenoplus_logo.png
    - assets/images/menu_bg.png
    - assets/images/classic_keno_bg.png
    - assets/images/mini_keno_bg.png
    - assets/images/kenoplus_element_bg.png
    - assets/images/game_bg.png

  fonts:
    - family: Grandstander
      fonts:
        - asset: assets/fonts/grandstander/Grandstander-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/grandstander/Grandstander-VariableFont_wght.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Italic-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/inter/Inter-VariableFont_opsz,wght.ttf
