import 'dart:math';

List<int> autoGenerateNumbersList({required int max, required int size}){
  final random = Random();

  final List<int> autoGeneratedList = [];
    while (autoGeneratedList.length < size) {
      autoGeneratedList.add(
        random.nextInt(max) + 1,
      ); // Random number between 1 and range
    }

  return autoGeneratedList;
}