import 'dart:math';

Set<int> autoGenerateNumbersList({required int max, required int size}) {
  final random = Random();

  // randomize unique numbers, no duplicates, not using set
  final autoGeneratedList = <int>{};
  while (autoGeneratedList.length < size) {
    final randomNumber = random.nextInt(max) + 1; // +1 to avoid 0
    autoGeneratedList.add(randomNumber);
  }

  return autoGeneratedList;
}
